@url = http://localhost:3003/generos

GET {{url}}

###
GET {{url}}/1

###
POST {{url}}
Content-Type: application/json

{
    "nome": "Aventura"
}

###
PUT {{url}}/1
Content-Type: application/json

{
    "nome" : "Fantasia Medieval"
}

###
DELETE {{url}}/1